version: "3.9"
services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kcpassword
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kcpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    volumes:
      - ./auth-service/keycloak/import/keycloak-realm-config.json:/opt/keycloak/data/import/keycloak-realm-config.json

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "4001:4001"
    environment:
      - AUTH_PORT=4001
    env_file:
      - .env
    depends_on:
      - mongodb
      - keycloak
    restart: always

  game-service:
    build:
      context: ./game-service
    ports:
      - "4002:4002"
    environment:
      - GAME_PORT=4002
    env_file:
      - .env

  quiz-service:
    build:
      context: ./quiz-service
    ports:
      - "4003:4003"
    environment:
      - QUIZ_PORT=4003
    env_file:
      - .env

  quiz-db:
    image: postgres:15
    container_name: quiz-db
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5433:5432"
    volumes:
      - quiz_data:/var/lib/postgresql/data
      - ./quiz-service/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongo_data:
  keycloak_data:
  quiz_data:
